
name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name : Checkout the repository
      uses: actions/checkout@v6
      
    - name: Use Node.js 24
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install dependencies
      run: npm install
      
    - name: Run integration tests
      run: npm test
  
  deploy: 
    needs: build_test   
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to productions
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{secrets.SERVICE_ID}}
          api-key: ${{ secrets.RENDER_TOKEN}}